### ISSUE TITLE
cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by olicc16** [HumanCompatibleAI/overcooked-demo#32]
I tried to build this demo from Mac computer with macOS Catalina Version 10.15.7, and it failed. The message says:

Starting demo_app_1 ... done
Attaching to demo_app_1
app_1  | Traceback (most recent call last):
app_1  |   File "app.py", line 12, in <module>
app_1  |     from flask import Flask, render_template, jsonify, request
app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
app_1  |     from jinja2 import escape
app_1  | ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)
demo_app_1 exited with code 1

Is it caused by OS or some package dependencies? Thanks!

**Comment by micahcarroll** [comment]
[This](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2) seems related. I'm not sure what is causing the issue here as I'm not very familiar with this portion of the stack of the code – the requirements.txt file has specific versions required (which should obviate this bug), but I'm not sure how that interacts with Docker or the rest of the code.

We'll be hiring a research engineer soon which can hopefully address this (and other) concerns!

**Comment by dvrijenhoek** [comment]
I've had the same issue, updating the versions of some of the dependencies seemed to have done the trick. Included you'll find the updated requirements.txt which hopefully works for you too.
[requirements.txt](https://github.com/HumanCompatibleAI/overcooked-demo/files/8669325/requirements.txt)

**Comment by alexlichtenstein** [comment]
Update been done #35
